- name: ping
  hosts: web
  tasks:
   - name: ping the serever
     ansible.builtin.ping:

- name: print
  hosts: web
  tasks: 
   - name: "print helloworld"
     ansible.builtin.debug:
     msg: "Hello World"

