- name: task vars
  hosts: local
  connection: local
  tasks:
  - name: task level vars
    vars:
      NAME: madhukar
      SURNAME: durgam
    ansible.builtin.debug:
      msg: "hello {{ NAME }} {{ SURNAME }}"