- name: prompting
  hosts: local
  connection: local
  vars_prompt:
  - name: NAME
    prompt: please enter your name
    private: false
  - name: SURNAME
    prompt: please enter your surname
    private: false
  - name: POSITION
    prompt: please enter your position
    private: true
  tasks:
  - name: print the prompt input
    ansible.builtin.debug:
      msg: "hello {{ NAME }} {{ SURNAME }} your position is {{ POSITION }}"

