- name: taking the vars from inventory file 
  hosts: web
  tasks:
  - name: taking the vars from inventory file 
    ansible.builtin.debug:
      msg: "hello {{ NAME }} {{ SURNAME }} your position is {{ POSITION }}"