- name: conditions
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: enter the number
    private: false
  tasks:
  - name: number is greater than or equal to 15
    ansible.builtin.debug:
      msg: "given number is greater than or equal to 15"
    when: number | int >= 15
  - name: number is lesser than 15
    ansible.builtin.debug:
      msg: "given number is lesser than 15"
    when: number | int < 15
 