- name: conditions
  hosts: local
  connection: local
  vars:
    my_number: 15
  vars_prompt:
  - name: number
    prompt: enter the number
    private: false
  tasks:
  - name: number is greater than or equal to 15
    ansible.builtin.debug:
      msg: "given number is greater than or equal to 15{{ name }}"
    when: number >= 15
  - name: number is lesser than 15
    ansible.builtin.debug:
      msg: "given number is lesser than 15{{ name }}"
    when: number < 15
 