- name: install packages
  hosts: local
  connection: local
  tasks:
  - name: installing packages
    ansible.builtin.package:
      name: "{{ items }}"
      state: installed
    loop:
    - nginx
    - gcc
    - zip