- name: present and absent packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: present and absent packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - {name: "nginx", state: absent"}
    - {name: "gcc", state: present }
    - {name: "zip", state: "absent" }